#!/bin/sh

catkin_make -DCATKIN_BLACKLIST_PACKAGES="mongodb_store;mongodb_store_msgs;mongodb_log;carla_ad_demo;carla_common;carla_msgs;carla_ackermann_msgs;carla_ros_scenario_runner_types;carla_waypoint_types;ros_compatibility;carla_ackermann_control;carla_ad_agent;carla_manual_control;carla_ros_bridge;carla_ros_scenario_runner;carla_spawn_objects;carla_twist_to_control;carla_walker_agent;carla_waypoint_publisher;rqt_carla_control;pcl_recorder;rviz_carla_plugin"
